export const SIGNAL_FACTORY = {
    KERNEL_FILE_UPLOAD: Symbol("KERNEL_FILE_UPLOADING"),
}

export const TRPC = {
    REACT_CLIENT_COMPONENTS_API: Symbol("TRPC_REACT_CLIENT_API"),
    VANILLA_CLIENT: Symbol("TRPC_VANILLA_CLIENT"),
}

export const REPOSITORY = {
    FILE_REPOSITORY: Symbol("FILE_REPOSITORY"),
    KERNEL_FILE_REPOSITORY: Symbol("KERNEL_FILE_REPOSITORY"),
}

export const CONTROLLERS = {
    KERNEL_FILE_UPLOAD_CONTROLLER: Symbol("KERNEL_FILE_UPLOAD_CONTROLLER"),
}