export const SIGNALS = {
}

export const CONSTANTS = {
    NEXT_AUTH_OPTIONS: Symbol.for('NEXT_AUTH_OPTIONS'),
}

export const TRPC = {
    APP_ROUTER: Symbol.for('APP_ROUTER'),
    REACT_SERVER_COMPONENTS_API: Symbol.for('SERVER_API'),
}

export const UTILS = {
    LOGGER_FACTORY: Symbol.for('LOGGER_FACTORY'),
}

export const OPENAI = {
    OPENAI_CLIENT: Symbol.for('OPENAI_CLIENT'),
    OPENAI_SOURCE_DATA_GATEWAY: Symbol.for('OPENAI_SOURCE_DATA_GATEWAY'),
}

export const KERNEL = {
    KERNEL_SDK: Symbol.for('KERNEL_OPENAPI_CLIENT'),
}

export const GATEWAYS = {
    AUTH_GATEWAY: Symbol.for('AUTH_GATEWAY'),
    AGENT_GATEWAY: Symbol.for('AGENT_GATEWAY'),
    CONVERSATION_GATEWAY: Symbol.for('CONVERSATION_GATEWAY'),
    RESEARCH_CONTEXT_GATEWAY: Symbol.for('RESEARCH_CONTEXT_GATEWAY'),
    VECTOR_STORE_GATEWAY: Symbol.for('VECTOR_STORE_GATEWAY'),
    KERNEL_SOURCE_DATA_GATEWAY: Symbol.for('KERNEL_SOURCE_DATA_GATEWAY'),
}

export const REPOSITORY = {
}

export const CONTROLLERS = {
    LIST_RESEARCH_CONTEXTS_CONTROLLER: Symbol.for('LIST_RESEARCH_CONTEXTS_CONTROLLER'),
}